
development:
  adapter: postgresql
  database: demodb
  host: localhost
  username: postgres
  password: dbadmin

test:
  adapter: postgresql
  database: demodbtest
  host: localhost
  username: postgres
  password: dbadmin

production:
  adapter: postgresql
  database: demodbproduction
  host: localhost
  username: postgres
  password: dbadmin
