
development:
  adapter: postgresql
  database: demodb
  host: localhost
  username: postgres
  password: dbadmin

test:
  adapter: postgresql
  database: demodbtest
  host: localhost
  username: postgres
  password: dbadmin

production:
  adapter: postgresql
  database: d2dc8clroo9roo
  host: ec2-107-20-245-187.compute-1.amazonaws.com
  username: uambymohlvsghm
  password: hhpDuuhHE8MyF-Cx1inpbHm3Yv
